// <auto-generated />
using System;
using B2B.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace B2B.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(B2BDbContext))]
    [Migration("20260417131756_AddDealerAndMsrpPrices")]
    partial class AddDealerAndMsrpPrices
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("app")
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("B2B.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BuyerUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("sysutcdatetime()");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("char(3)");

                    b.Property<decimal>("GrandTotal")
                        .HasColumnType("decimal(19,4)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<long>("OrderNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("OrderNumber"));

                    b.Property<byte[]>("RowVer")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("SellerUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ShippingTotal")
                        .HasColumnType("decimal(19,4)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(19,4)");

                    b.Property<decimal>("TaxTotal")
                        .HasColumnType("decimal(19,4)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("OrderId");

                    b.HasAlternateKey("OrderNumber");

                    b.HasIndex("BuyerUserId", "CreatedAtUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_Orders_Buyer_CreatedAt");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("BuyerUserId", "CreatedAtUtc"), new[] { "Status", "OrderNumber", "GrandTotal", "CurrencyCode" });

                    b.HasIndex("SellerUserId", "Status", "CreatedAtUtc")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("IX_Orders_Seller_Status_CreatedAt");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("SellerUserId", "Status", "CreatedAtUtc"), new[] { "OrderNumber", "BuyerUserId", "GrandTotal", "CurrencyCode" });

                    b.ToTable("Orders", "app", t =>
                        {
                            t.HasCheckConstraint("CK_Orders_Totals_NonNegative", "Subtotal >= 0 AND TaxTotal >= 0 AND ShippingTotal >= 0 AND GrandTotal >= 0");
                        });
                });

            modelBuilder.Entity("B2B.Domain.Entities.OrderItem", b =>
                {
                    b.Property<Guid>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("LineNumber")
                        .HasColumnType("int");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ProductSku")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVer")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(19,4)");

                    b.HasKey("OrderItemId");

                    b.HasIndex("OrderId");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("OrderId"), new[] { "ProductId", "ProductSku", "ProductName", "UnitPrice", "Quantity" });

                    b.HasIndex("OrderId", "LineNumber")
                        .IsUnique();

                    b.HasIndex("ProductId", "OrderId");

                    b.ToTable("OrderItems", "app", t =>
                        {
                            t.HasCheckConstraint("CK_OrderItems_Qty_Positive", "Quantity > 0");

                            t.HasCheckConstraint("CK_OrderItems_UnitPrice_NonNegative", "UnitPrice >= 0");
                        });
                });

            modelBuilder.Entity("B2B.Domain.Entities.OrderSubmission", b =>
                {
                    b.Property<Guid>("OrderSubmissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BuyerUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("sysutcdatetime()");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("SellerUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("OrderSubmissionId");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("IX_OrderSubmissions_OrderId");

                    b.HasIndex("BuyerUserId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("UX_OrderSubmissions_Buyer_Key");

                    b.ToTable("OrderSubmissions", "app");
                });

            modelBuilder.Entity("B2B.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("sysutcdatetime()");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("char(3)");

                    b.Property<decimal>("DealerPrice")
                        .HasColumnType("decimal(19,4)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal>("MsrpPrice")
                        .HasColumnType("decimal(19,4)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte[]>("RowVer")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("SellerUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("ProductId");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Products_Name_Search");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("Name"), new[] { "SellerUserId", "DealerPrice", "MsrpPrice", "CurrencyCode", "IsActive" });

                    b.HasIndex("SellerUserId", "IsActive");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("SellerUserId", "IsActive"), new[] { "Name", "DealerPrice", "MsrpPrice", "CurrencyCode", "StockQuantity" });

                    b.HasIndex("SellerUserId", "Sku")
                        .IsUnique();

                    b.ToTable("Products", "app", t =>
                        {
                            t.HasCheckConstraint("CK_Products_DealerPrice_NonNegative", "DealerPrice >= 0");

                            t.HasCheckConstraint("CK_Products_MsrpPrice_NonNegative", "MsrpPrice >= 0");

                            t.HasCheckConstraint("CK_Products_Stock_NonNegative", "StockQuantity >= 0");
                        });
                });

            modelBuilder.Entity("B2B.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("sysutcdatetime()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleId");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.ToTable("Roles", "app");
                });

            modelBuilder.Entity("B2B.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("sysutcdatetime()");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varbinary(512)");

                    b.Property<byte[]>("PasswordSalt")
                        .HasMaxLength(128)
                        .HasColumnType("varbinary(128)");

                    b.Property<byte[]>("RowVer")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique();

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("NormalizedEmail"), new[] { "Email", "DisplayName", "IsActive" });

                    b.ToTable("Users", "app");
                });

            modelBuilder.Entity("B2B.Domain.Entities.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId", "UserId");

                    b.ToTable("UserRoles", "app");
                });

            modelBuilder.Entity("B2B.Domain.Entities.Order", b =>
                {
                    b.HasOne("B2B.Domain.Entities.User", "BuyerUser")
                        .WithMany("OrdersAsBuyer")
                        .HasForeignKey("BuyerUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("B2B.Domain.Entities.User", "SellerUser")
                        .WithMany("OrdersAsSeller")
                        .HasForeignKey("SellerUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("BuyerUser");

                    b.Navigation("SellerUser");
                });

            modelBuilder.Entity("B2B.Domain.Entities.OrderItem", b =>
                {
                    b.HasOne("B2B.Domain.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("B2B.Domain.Entities.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("B2B.Domain.Entities.OrderSubmission", b =>
                {
                    b.HasOne("B2B.Domain.Entities.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("B2B.Domain.Entities.Product", b =>
                {
                    b.HasOne("B2B.Domain.Entities.User", "SellerUser")
                        .WithMany("ProductsAsSeller")
                        .HasForeignKey("SellerUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("SellerUser");
                });

            modelBuilder.Entity("B2B.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("B2B.Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("B2B.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("B2B.Domain.Entities.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("B2B.Domain.Entities.Product", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("B2B.Domain.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("B2B.Domain.Entities.User", b =>
                {
                    b.Navigation("OrdersAsBuyer");

                    b.Navigation("OrdersAsSeller");

                    b.Navigation("ProductsAsSeller");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
